<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // Drop the existing constraint generated by PostgreSQL
        DB::statement("ALTER TABLE transfers DROP CONSTRAINT transfers_status_check;");

        // Add the new constraint with 'failed' included
        DB::statement("ALTER TABLE transfers ADD CONSTRAINT transfers_status_check CHECK (status::text = ANY (ARRAY['pending'::text, 'completed'::text, 'declined'::text, 'failed'::text]));");
    }

    public function down(): void
    {
        DB::statement("ALTER TABLE transfers DROP CONSTRAINT transfers_status_check;");
        DB::statement("ALTER TABLE transfers ADD CONSTRAINT transfers_status_check CHECK (status::text = ANY (ARRAY['pending'::text, 'completed'::text, 'declined'::text]));");
    }
};